### PR TITLE
style: Add pep8 check and format code to comply.

### PR DESCRIPTION
**Pull request by leamas**
Not much to say. This is not my style, this is the official python style. I don't like all parts of iot, but recognize the benefits of a uniform, well.defined stamdard.

### CODE REVIEW

**Comment by leamas** [comment]
Note the top commit message

**Comment by leamas** [comment]
See also: https://www.python.org/dev/peps/pep-0008

**Comment by bengtmartensson** [comment]
Merged. I "had to" change a few things, though. 

Thank you very much for your efforts!!

**Comment by leamas** [comment]
OK,, you are welcome. Busy doing other things for now, back later. In the meantime: in the meantime there is "make pylint" which igives some hints. (dnf install python3.pylint)

**Pull request merged**
